export default {
  HOME: '/',
  LOGIN: '/login',
  CONFIRM_EMAIL: '/confirm-email',
  SUCCESS: '/success',
  SET_2FA: '/set-2fa',
  WELCOME_BACK: '/welcome-back',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  PROFILE: {
    SETTINGS: '/profile',
    EDIT_FULLNAME: '/profile/edit-fullname',
    EDIT_EMAIL: '/profile/edit-email',
    EDIT_PHONENUMBER: '/profile/edit-phonenumber',
    EDIT_PASSWORD: '/profile/edit-password',
    REQUEST_VERIFICATION: '/profile/request-verification',
  },
  USER_DASHBOARD: '/dashboard',
  EDIT_TRADE: '/trade/228/edit',
};
