export const GET_REVIEWS_BY_USERNAME_REQUEST = 'user/reviews/GET_REVIEWS_BY_USERNAME_REQUEST';
export const GET_REVIEWS_BY_USERNAME_SUCCESS = 'user/reviews/GET_REVIEWS_BY_USERNAME_SUCCESS';
export const GET_REVIEWS_BY_USERNAME_ERROR = 'user/reviews/GET_REVIEWS_BY_USERNAME_ERROR';

export const GET_LIKES_COUNT_BY_USERNAME_REQUEST = 'user/reviews/GET_LIKES_COUNT_BY_USERNAME_REQUEST';
export const GET_LIKES_COUNT_BY_USERNAME_SUCCESS = 'user/reviews/GET_LIKES_COUNT_BY_USERNAME_SUCCESS';
export const GET_LIKES_COUNT_BY_USERNAME_ERROR = 'user/reviews/GET_LIKES_COUNT_BY_USERNAME_ERROR';
