export const data = [
  {
    key: 1,
    transactionLimits: '1,000 - 2,655 USD',
    paymentMethod: 'Cash deposite',
    seller: 'luckycoinz360',
    location: 'United States',
    priceBtc: '8,199.52 USD',
    action: 'Buy',
  },
  {
    key: 2,
    transactionLimits: '1,000 - 2,655 USD',
    paymentMethod: 'Cash deposite',
    seller: 'luckycoinz360',
    location: 'United States',
    priceBtc: '8,199.52 USD',
    action: 'Buy',
  },
  {
    key: 3,
    transactionLimits: '1,000 - 2,655 USD',
    paymentMethod: 'Cash deposite',
    seller: 'luckycoinz360',
    location: 'United States',
    priceBtc: '8,199.52 USD',
    action: 'Buy',
  },
  {
    key: 4,
    transactionLimits: '1,000 - 2,655 USD',
    paymentMethod: 'Cash deposite',
    seller: 'luckycoinz360',
    location: 'United States',
    priceBtc: '8,199.52 USD',
    action: 'Buy',
  },
  {
    key: 5,
    transactionLimits: '1,000 - 2,655 USD',
    paymentMethod: 'Cash deposite',
    seller: 'luckycoinz360',
    location: 'United States',
    priceBtc: '8,199.52 USD',
    action: 'Buy',
  },
  {
    key: 6,
    transactionLimits: '1,000 - 2,655 USD',
    paymentMethod: 'Cash deposite',
    seller: 'luckycoinz360',
    location: 'United States',
    priceBtc: '8,199.52 USD',
    action: 'Buy',
  },
  {
    key: 7,
    transactionLimits: '1,000 - 2,655 USD',
    paymentMethod: 'Cash deposite',
    seller: 'luckycoinz360',
    location: 'United States',
    priceBtc: '8,199.52 USD',
    action: 'Buy',
  },
];
