export const REFRESHING_TOKEN_REQUEST = 'global/REFRESHING_TOKEN_REQUEST';
export const REFRESHING_TOKEN_SUCCESS = 'global/REFRESHING_TOKEN_SUCCESS';
export const REFRESHING_TOKEN_ERROR = 'global/REFRESHING_TOKEN_ERROR';

export const PERMISSION_NOTIFICATION = 'global/PERMISSION_NOTIFICATION';
