export const GET_CREATED_REQUEST = 'ads/ads/GET_CREATED_REQUEST';
export const GET_CREATED_SUCCESS = 'ads/ads/GET_CREATED_SUCCESS';
export const GET_CREATED_ERROR = 'ads/ads/GET_CREATED_ERROR';

export const GET_MY_CREATED_REQUEST = 'ads/ads/GET_MY_CREATED_REQUEST';
export const GET_MY_CREATED_SUCCESS = 'ads/ads/GET_MY_CREATED_SUCCESS';
export const GET_MY_CREATED_ERROR = 'ads/ads/GET_MY_CREATED_ERROR';
