export const GET_ADS_BY_USERNAME_REQUEST = 'user/ads/GET_ADS_BY_USERNAME_REQUEST';
export const GET_ADS_BY_USERNAME_SUCCESS = 'user/ads/GET_ADS_BY_USERNAME_SUCCESS';
export const GET_ADS_BY_USERNAME_ERROR = 'user/ads/GET_ADS_BY_USERNAME_ERROR';
