/* Getting user profile data */
export const GET_PROFILE_REQUEST = 'me/GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'me/GET_PROFILE_SUCCESS';
export const GET_PROFILE_ERROR = 'me/GET_PROFILE_ERROR';

export const GET_SMS_CODE_REQUEST = 'me/GET_SMS_CODE_REQUEST';
export const GET_SMS_CODE_SUCCESS = 'me/GET_SMS_CODE_SUCCESS';
export const GET_SMS_CODE_ERROR = 'me/GET_SMS_CODE_ERROR';

export const EDIT_EMAIL_REQUEST = 'me/EDIT_EMAIL_REQUEST';
export const EDIT_EMAIL_SUCCESS = 'me/EDIT_EMAIL_SUCCESS';
export const EDIT_EMAIL_ERROR = 'me/EDIT_EMAIL_ERROR';

export const EDIT_FULLNAME_REQUEST = 'me/EDIT_FULLNAME_REQUEST';
export const EDIT_FULLNAME_SUCCESS = 'me/EDIT_FULLNAME_SUCCESS';
export const EDIT_FULLNAME_ERROR = 'me/EDIT_FULLNAME_ERROR';

export const EDIT_PHONENUMBER_REQUEST = 'me/EDIT_PHONENUMBER_REQUEST';
export const EDIT_PHONENUMBER_SUCCESS = 'me/EDIT_PHONENUMBER_SUCCESS';
export const EDIT_PHONENUMBER_ERROR = 'me/EDIT_PHONENUMBER_ERROR';

export const EDIT_PASSWORD_REQUEST = 'me/EDIT_PASSWORD_REQUEST';
export const EDIT_PASSWORD_SUCCESS = 'me/EDIT_PASSWORD_SUCCESS';
export const EDIT_PASSWORD_ERROR = 'me/EDIT_PASSWORD_ERROR';
